import { useState } from 'react'
import C1Chatbot from './components/C1Chatbot'
import authService from './services/AuthService'

function App() {
    const [user, setUser] = useState(null);
    const [authToken, setAuthToken] = useState('');
    const [isLoading, setIsLoading] = useState(false);

    // Real-world login flow
    const handleLogin = async () => {
        setIsLoading(true);
        try {
            const { user, c1Token } = await authService.login('C1User');
            setUser(user);
            setAuthToken(c1Token);
        } catch (error) {
            console.error('Login failed:', error);
        } finally {
            setIsLoading(false);
        }
    };

    const handleLogout = () => {
        authService.logout();
        setUser(null);
        setAuthToken('');
    };

    return (
        <div className="app">
            <header className="header">
                <div className="header-content">
                    <div className="logo">
                        <div className="logo-icon">🤖</div>
                        <span>C1 Chatbot Portal</span>
                    </div>
                    <div className="header-actions">
                        {!user ? (
                            <button
                                className="btn-login"
                                onClick={handleLogin}
                                disabled={isLoading}
                            >
                                {isLoading ? 'Authenticating...' : 'Sign In'}
                            </button>
                        ) : (
                            <div className="user-profile">
                                <span className="user-name">Welcome, {user.username}</span>
                                <button className="btn-logout" onClick={handleLogout}>
                                    Sign Out
                                </button>
                            </div>
                        )}
                    </div>
                </div>
            </header>

            <main className="main-content">
                <section className="hero-section">
                    <h1 className="hero-title">
                        Enterprise Support <span>Redefined</span>
                    </h1>
                    <p className="hero-description">
                        Experience seamless, automated support with the integrated C1 Chatbot.
                        Sign in above to access your personalized support dashboard and tickets.
                    </p>

                    <div className="auth-status-card">
                        <div className="status-header">
                            <h3>System Status</h3>
                            <div className={`status-dot ${user ? 'active' : ''}`}></div>
                        </div>

                        <div className="info-grid">
                            <div className="info-item">
                                <label>Authentication</label>
                                <span>{user ? 'Secured SSO Session' : 'Guest Access'}</span>
                            </div>
                            <div className="info-item">
                                <label>Access Level</label>
                                <span>{user ? 'Verified User' : 'Standard'}</span>
                            </div>
                        </div>

                        {user && (
                            <div className="token-management">
                                <label>C1 Access Token</label>
                                <input
                                    type="password"
                                    value={authToken || 'AUTOMATIC_TOKEN_LOADED'}
                                    readOnly
                                    className="token-display"
                                />
                                <p className="helper-text">
                                    This token was securely generated by the backend and passed to the chatbot.
                                </p>
                            </div>
                        )}
                    </div>
                </section>
            </main>

            <footer className="footer">
                <p>© 2026 C1 Portal • Implementation based on C1 Production Standard</p>
            </footer>

            {/* C1 Chatbot - Production Bridge */}
            <C1Chatbot selectedProject="combined_c1_all" token={authToken} />
        </div>
    )
}

export default App
